name: CI
on: [pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
              node: [ '12' ]
        name: Node ${{ matrix.node }} sample
        steps:
            - uses: actions/checkout@v2
            - run: npm install
            - run: npm run test